<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;

class ActRequestSubmission extends Model
{
    use HasUuids;

    protected static function booted(): void
    {
        static::updated(function (self $submission): void {
            if (!$submission->wasChanged('status')) {
                return;
            }

            $oldStatus = (string) $submission->getOriginal('status');
            $newStatus = (string) $submission->status;

            $submission->sendStatusChangeEmail($oldStatus, $newStatus);
        });
    }

    protected $fillable = [
        'tracking_number',
        'tracking_token',
        'unique_key_value',
        'requested_act_id',
        'emitter_administration_id',
        'direction_code',
        'recipient_administration_id',
        'motif',
        'requested_document_name',
        'applicant_full_name',
        'applicant_email',
        'applicant_phone',
        'applicant_payload',
        'attachments',
        'auto_generated_document_id',
        'auto_generated_at',
        'validated_by_user_id',
        'validated_at',
        'status',
    ];

    protected $casts = [
        'applicant_payload' => 'array',
        'attachments' => 'array',
        'auto_generated_at' => 'datetime',
        'validated_at' => 'datetime',
    ];

    public function requestedAct()
    {
        return $this->belongsTo(RequestedAct::class, 'requested_act_id');
    }

    public function administration()
    {
        return $this->belongsTo(IssuingAdministration::class, 'emitter_administration_id');
    }

    public function recipientAdministration()
    {
        return $this->belongsTo(RecipientAdministration::class, 'recipient_administration_id');
    }

    public function autoGeneratedDocument()
    {
        return $this->belongsTo(Document::class, 'auto_generated_document_id');
    }

    public function validatedBy()
    {
        return $this->belongsTo(User::class, 'validated_by_user_id');
    }

    private function resolveSmtpSetting(): ?AdministrationSmtpSetting
    {
        $administrationId = trim((string) ($this->emitter_administration_id ?? ''));
        if ($administrationId === '') {
            $administrationId = trim((string) ($this->recipient_administration_id ?? ''));
        }

        if ($administrationId === '') {
            return null;
        }

        return AdministrationSmtpSetting::forAdministration($administrationId, 'emitter')
            ?? AdministrationSmtpSetting::forAdministration($administrationId, 'recipient');
    }

    private function applyScopedSmtpConfiguration(AdministrationSmtpSetting $smtp): void
    {
        config([
            'mail.default' => 'smtp',
            'mail.mailers.smtp.host' => $smtp->mail_host,
            'mail.mailers.smtp.port' => $smtp->mail_port ?? 587,
            'mail.mailers.smtp.username' => $smtp->mail_username,
            'mail.mailers.smtp.password' => $smtp->mail_password,
            'mail.mailers.smtp.encryption' => $smtp->mail_encryption ?: null,
            'mail.mailers.smtp.timeout' => 10,
            'mail.from.address' => $smtp->mail_from_address,
            'mail.from.name' => $smtp->mail_from_name ?? config('app.name'),
        ]);
    }

    private function configureMailerForSubmission(): ?string
    {
        $smtp = $this->resolveSmtpSetting();
        if (!$smtp) {
            return "Aucune configuration SMTP d'administration n'a ete trouvee pour cette demande.";
        }

        if (!$smtp->mail_host || !$smtp->mail_from_address) {
            return "La configuration SMTP d'administration est incomplete (hote ou expediteur manquant).";
        }

        $this->applyScopedSmtpConfiguration($smtp);
        return null;
    }

    private function sendStatusChangeEmail(string $oldStatus, string $newStatus): void
    {
        $recipientEmail = trim((string) ($this->applicant_email ?? ''));
        if ($recipientEmail === '' || !filter_var($recipientEmail, FILTER_VALIDATE_EMAIL)) {
            return;
        }

        $labels = [
            'pending' => 'En attente',
            'in_progress' => 'En cours de traitement',
            'sent' => 'Envoyee',
            'recu' => 'Recu',
            'treated' => 'Terminee',
            'rejected' => 'Refusee',
        ];

        $oldLabel = $labels[$oldStatus] ?? ucfirst(str_replace('_', ' ', $oldStatus));
        $newLabel = $labels[$newStatus] ?? ucfirst(str_replace('_', ' ', $newStatus));

        $trackingNumber = (string) ($this->tracking_number ?: '-');
        $trackingUrl = '';

        try {
            if (!empty($this->tracking_token)) {
                $trackingUrl = route('public.act-requests.track', ['tracking_token' => $this->tracking_token]);
            }
        } catch (\Throwable $e) {
            $trackingUrl = '';
        }

        $subject = 'Evolution de votre demande d\'acte (' . $trackingNumber . ')';
        $body = "Bonjour,\n\n"
            . "Le statut de votre demande d'acte a change.\n"
            . "Numero de traitement : {$trackingNumber}\n"
            . "Ancien statut : {$oldLabel}\n"
            . "Nouveau statut : {$newLabel}\n";

        if ($trackingUrl !== '') {
            $body .= "\nSuivi de votre demande : {$trackingUrl}\n";
        }

        $body .= "\nMerci.";

        $smtpError = $this->configureMailerForSubmission();
        if ($smtpError !== null) {
            Log::error('ActRequestSubmission status email config unavailable', [
                'submission_id' => (string) $this->id,
                'tracking_number' => (string) $this->tracking_number,
                'recipient_email' => $recipientEmail,
                'emitter_administration_id' => (string) ($this->emitter_administration_id ?? ''),
                'recipient_administration_id' => (string) ($this->recipient_administration_id ?? ''),
                'from_status' => $oldStatus,
                'to_status' => $newStatus,
                'error' => $smtpError,
            ]);
            return;
        }

        try {
            Mail::raw($body, function ($message) use ($recipientEmail, $subject): void {
                $message->to($recipientEmail)->subject($subject);
            });
        } catch (\Throwable $e) {
            Log::error('ActRequestSubmission status email failed', [
                'submission_id' => (string) $this->id,
                'tracking_number' => (string) $this->tracking_number,
                'recipient_email' => $recipientEmail,
                'from_status' => $oldStatus,
                'to_status' => $newStatus,
                'error' => $e->getMessage(),
            ]);
        }
    }
}
