<?php

namespace App\Models;

use App\Services\NotificationService;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;

class ActRequestSubmission extends Model
{
    use HasUuids;

    protected static function booted(): void
    {
        static::updated(function (self $submission): void {
            if (!$submission->wasChanged('status')) {
                return;
            }

            $oldStatus = (string) $submission->getOriginal('status');
            $newStatus = (string) $submission->status;

            $submission->sendStatusChangeEmail($oldStatus, $newStatus);
        });
    }

    protected $fillable = [
        'tracking_number',
        'tracking_token',
        'unique_key_value',
        'requested_act_id',
        'emitter_administration_id',
        'direction_code',
        'recipient_administration_id',
        'motif',
        'requested_document_name',
        'applicant_full_name',
        'applicant_email',
        'applicant_phone',
        'applicant_payload',
        'attachments',
        'auto_generated_document_id',
        'auto_generated_at',
        'validated_by_user_id',
        'validated_at',
        'status',
    ];

    protected $casts = [
        'applicant_payload' => 'array',
        'attachments' => 'array',
        'auto_generated_at' => 'datetime',
        'validated_at' => 'datetime',
    ];

    public function requestedAct()
    {
        return $this->belongsTo(RequestedAct::class, 'requested_act_id');
    }

    public function administration()
    {
        return $this->belongsTo(IssuingAdministration::class, 'emitter_administration_id');
    }

    public function recipientAdministration()
    {
        return $this->belongsTo(RecipientAdministration::class, 'recipient_administration_id');
    }

    public function autoGeneratedDocument()
    {
        return $this->belongsTo(Document::class, 'auto_generated_document_id');
    }

    public function validatedBy()
    {
        return $this->belongsTo(User::class, 'validated_by_user_id');
    }

    private function resolveAdministrationSmtpSetting(): ?AdministrationSmtpSetting
    {
        $emitterId = trim((string) ($this->emitter_administration_id ?? ''));
        if ($emitterId !== '') {
            $smtp = AdministrationSmtpSetting::forAdministration($emitterId, 'emitter');
            if ($smtp) {
                return $smtp;
            }
        }

        $recipientId = trim((string) ($this->recipient_administration_id ?? ''));
        if ($recipientId !== '') {
            $smtp = AdministrationSmtpSetting::forAdministration($recipientId, 'recipient');
            if ($smtp) {
                return $smtp;
            }
        }

        return null;
    }

    private function applyAdministrationSmtpConfiguration(AdministrationSmtpSetting $smtp): void
    {
        config([
            'mail.default'                 => 'smtp',
            'mail.mailers.smtp.host'       => $smtp->mail_host,
            'mail.mailers.smtp.port'       => $smtp->mail_port ?? 587,
            'mail.mailers.smtp.username'   => $smtp->mail_username,
            'mail.mailers.smtp.password'   => $smtp->mail_password,
            'mail.mailers.smtp.encryption' => $smtp->mail_encryption ?: null,
            'mail.mailers.smtp.timeout'    => 10,
            'mail.from.address'            => $smtp->mail_from_address,
            'mail.from.name'               => $smtp->mail_from_name ?? config('app.name'),
        ]);
    }

    private function configureActRequestMailerForSubmission(): ?string
    {
        $smtp = $this->resolveAdministrationSmtpSetting();
        if (!$smtp) {
            return 'Aucune configuration SMTP d\'administration n\'a ete trouvee pour la demande d\'acte ' . ($this->tracking_number ?: $this->id);
        }

        if (!$smtp->mail_host || !$smtp->mail_from_address) {
            return 'La configuration SMTP d\'administration est incomplete (hote ou expediteur manquant) pour la demande d\'acte ' . ($this->tracking_number ?: $this->id);
        }

        $this->applyAdministrationSmtpConfiguration($smtp);

        return null;
    }

    private function sendStatusChangeEmail(string $oldStatus, string $newStatus): void
    {
        $recipientEmail = trim((string) ($this->applicant_email ?? ''));
        if ($recipientEmail === '' || !filter_var($recipientEmail, FILTER_VALIDATE_EMAIL)) {
            return;
        }

        $labels = [
            'pending' => 'En attente',
            'in_progress' => 'En cours de traitement',
            'sent' => 'Envoyee',
            'recu' => 'Recu',
            'treated' => 'Terminee',
            'rejected' => 'Refusee',
        ];

        $oldLabel = $labels[$oldStatus] ?? ucfirst(str_replace('_', ' ', $oldStatus));
        $newLabel = $labels[$newStatus] ?? ucfirst(str_replace('_', ' ', $newStatus));

        $trackingNumber = (string) ($this->tracking_number ?: '-');
        $trackingUrl = '';

        try {
            if (!empty($this->tracking_token)) {
                $trackingUrl = route('public.act-requests.track', ['tracking_token' => $this->tracking_token]);
            }
        } catch (\Throwable $e) {
            $trackingUrl = '';
        }

        $this->notifyMatchingUserAccount($recipientEmail, $oldStatus, $newStatus, $oldLabel, $newLabel, $trackingNumber, $trackingUrl);
        $this->notifyRelevantInternalRecipients($oldStatus, $newStatus, $oldLabel, $newLabel, $trackingNumber, $trackingUrl);

        $subject = 'Evolution de votre demande d\'acte (' . $trackingNumber . ')';
        $body = "Bonjour,\n\n"
            . "Le statut de votre demande d'acte a change.\n"
            . "Numero de traitement : {$trackingNumber}\n"
            . "Ancien statut : {$oldLabel}\n"
            . "Nouveau statut : {$newLabel}\n";

        if ($trackingUrl !== '') {
            $body .= "\nSuivi de votre demande : {$trackingUrl}\n";
        }

        $body .= "\nMerci.";

$smtpError = $this->configureActRequestMailerForSubmission();
if ($smtpError !== null) {
    Log::error('ActRequestSubmission status email failed: administration SMTP configuration unavailable.', [
        'submission_id' => (string) $this->id,
        'tracking_number' => (string) $this->tracking_number,
        'recipient_email' => $recipientEmail,
        'emitter_administration_id' => (string) ($this->emitter_administration_id ?? ''),
        'recipient_administration_id' => (string) ($this->recipient_administration_id ?? ''),
        'from_status' => $oldStatus,
        'to_status' => $newStatus,
        'error' => $smtpError,
    ]);

    return;
}

try {
    Mail::raw($body, function ($message) use ($recipientEmail, $subject): void {
        $message->to($recipientEmail)->subject($subject);
    });
} catch (\Throwable $e) {
    Log::error('ActRequestSubmission status email failed.', [
        'submission_id' => (string) $this->id,
        'tracking_number' => (string) $this->tracking_number,
        'recipient_email' => $recipientEmail,
        'from_status' => $oldStatus,
        'to_status' => $newStatus,
        'error' => $e->getMessage(),
    ]);
}
    }

    private function notifyRelevantInternalRecipients(
        string $oldStatus,
        string $newStatus,
        string $oldLabel,
        string $newLabel,
        string $trackingNumber,
        string $trackingUrl
    ): void {
        $candidateUserIds = [];
        $seenUserIds = [];
        $applicantEmail = mb_strtolower(trim((string) ($this->applicant_email ?? '')));

        foreach ([
            ['type' => 'emitter', 'id' => $this->emitter_administration_id],
            ['type' => 'recipient', 'id' => $this->recipient_administration_id],
        ] as $scope) {
            $scopeType = $scope['type'] ?? null;
            $scopeId = $scope['id'] ?? null;

            if (!$scopeType || !$scopeId) {
                continue;
            }

            $assignmentUserIds = UserDirectionAssignment::query()
                ->where('direction_scope_type', $scopeType)
                ->where('direction_scope_id', $scopeId)
                ->pluck('user_id')
                ->filter(fn ($userId) => is_string($userId) || is_numeric($userId))
                ->map(fn ($userId) => (string) $userId)
                ->all();

            $profileUserIds = User::query()
                ->whereHas('profile', function ($query) use ($scopeType, $scopeId): void {
                    $query->where('administration_type', $scopeType)
                        ->where('administration_id', $scopeId);
                })
                ->pluck('id')
                ->filter(fn ($userId) => is_string($userId) || is_numeric($userId))
                ->map(fn ($userId) => (string) $userId)
                ->all();

            foreach (array_merge($assignmentUserIds, $profileUserIds) as $userId) {
                $userId = (string) $userId;
                if ($userId === '' || isset($seenUserIds[$userId])) {
                    continue;
                }

                $seenUserIds[$userId] = true;
                $candidateUserIds[] = $userId;
            }
        }

        if (!empty($this->direction_code)) {
            $directionCode = strtoupper(trim((string) $this->direction_code));
            if ($directionCode !== '') {
                $subEntity = SubEntity::query()
                    ->where('scope_type', 'emitter')
                    ->where('scope_id', $this->emitter_administration_id)
                    ->where('is_active', true)
                    ->whereRaw('UPPER(code) = ?', [$directionCode])
                    ->first();

                if ($subEntity && trim((string) ($subEntity->manager_email ?? '')) !== '') {
                    $managerUser = User::query()
                        ->whereRaw('LOWER(email) = ?', [mb_strtolower(trim((string) $subEntity->manager_email))])
                        ->first();

                    if ($managerUser) {
                        $userId = (string) $managerUser->id;
                        if (!isset($seenUserIds[$userId])) {
                            $seenUserIds[$userId] = true;
                            $candidateUserIds[] = $userId;
                        }
                    }
                }
            }
        }

        if (empty($candidateUserIds)) {
            return;
        }

        $query = User::query()
            ->whereIn('id', $candidateUserIds)
            ->whereIn('role', ['admin', 'manager', 'signer'])
            ->orderBy('name');

        $actionUrl = $trackingUrl !== '' ? $trackingUrl : (function (): ?string {
            try {
                return route('act-requests.index');
            } catch (\Throwable $e) {
                return null;
            }
        })();

        foreach ($query->get() as $user) {
            $recipientEmail = mb_strtolower(trim((string) ($user->email ?? '')));
            if ($recipientEmail === '' || $recipientEmail === $applicantEmail) {
                continue;
            }

            $message = sprintf(
                'La demande d\'acte %s a change de statut : %s → %s.',
                $trackingNumber,
                $oldLabel,
                $newLabel
            );

            try {
                NotificationService::notify(
                    recipientId: (string) $user->id,
                    type: 'info',
                    title: 'Mise à jour d\'une demande d\'acte',
                    message: $message,
                    actionUrl: $actionUrl ?? route('act-requests.index'),
                );
            } catch (\Throwable $e) {
                Log::warning('ActRequestSubmission internal status notification failed', [
                    'submission_id' => (string) $this->id,
                    'tracking_number' => (string) $this->tracking_number,
                    'recipient_user_id' => (string) $user->id,
                    'recipient_email' => (string) $user->email,
                    'from_status' => $oldStatus,
                    'to_status' => $newStatus,
                    'error' => $e->getMessage(),
                ]);
            }
        }
    }

    private function notifyMatchingUserAccount(
        string $recipientEmail,
        string $oldStatus,
        string $newStatus,
        string $oldLabel,
        string $newLabel,
        string $trackingNumber,
        string $trackingUrl
    ): void {
        $user = User::query()
            ->whereRaw('LOWER(email) = ?', [mb_strtolower(trim($recipientEmail))])
            ->first();

        if (!$user) {
            return;
        }

        $actionUrl = $trackingUrl !== '' ? $trackingUrl : route('act-requests.index');
        $message = sprintf(
            'Votre demande d\'acte %s a change de statut : %s → %s.',
            $trackingNumber,
            $oldLabel,
            $newLabel
        );

        try {
            NotificationService::notify(
                recipientId: (string) $user->id,
                type: 'info',
                title: 'Mise à jour de votre demande d\'acte',
                message: $message,
                actionUrl: $actionUrl,
            );
        } catch (\Throwable $e) {
            Log::warning('ActRequestSubmission matching user notification failed', [
                'submission_id' => (string) $this->id,
                'tracking_number' => (string) $this->tracking_number,
                'recipient_user_id' => (string) $user->id,
                'recipient_email' => (string) $user->email,
                'from_status' => $oldStatus,
                'to_status' => $newStatus,
                'error' => $e->getMessage(),
            ]);
        }
    }
}
